### ISSUE TITLE
usb.core.USBError: [Errno 16] Resource busy

### ISSUE THREAD

**Issue by ChaimaZnaidi** [charlysan/pyrfidhid#9]
I am using an RFID reader with Raspberry Pi 3 and when I execute that code, I am getting this error
```
Cannot write USB feature report. Maybe incompatible device?
Traceback (most recent call last):
  File "/home/pi/PFE/RFID/read.py", line 11, in <module>
    payload_response = rfid.read_tag()
  File "/usr/local/lib/python3.9/dist-packages/rfidhid/core.py", line 96, in read_tag
    response = self.hid.set_feature_report(1, buff)
  File "/usr/local/lib/python3.9/dist-packages/rfidhid/usb_hid.py", line 52, in set_feature_report
    return self.dev.ctrl_transfer(
  File "/usr/local/lib/python3.9/dist-packages/usb/core.py", line 1080, in ctrl_transfer
    self._ctx.managed_claim_interface(self, interface_number)
  File "/usr/local/lib/python3.9/dist-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/usb/core.py", line 178, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/local/lib/python3.9/dist-packages/usb/backend/libusb1.py", line 829, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/local/lib/python3.9/dist-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy
```

Does anyone know how to solve it please ?

**Comment by charlysan** [comment]
I've tested it out in RPI without any issues. Which python version are you using @ChaimaZnaidi?

**Comment by darkman7hr** [comment]
I'm getting same issue.

root@pi4:/tmp/pyrfidhid/cli# python  ./rfid_cli.py -r --usb-vid 2303 --usb-pid 9
Cannot write USB feature report. Maybe incompatible device?

How to know which one is compatibile? all look same?

**Comment by rgbetanco** [comment]
_check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/home/rgbetanco/Documents/Python/Tests/env/lib/python3.11/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy


Same here
